version: "3.6"
services:
  gams:
    build: .
#    command: bash -c "/opt/gams/gams25.0_linux_x64_64_sfx/gams"
    stdin_open: true
    container_name: rti-gams-25.0.3
    tty: true
    volumes:
      - ./sourceandstudies/:/workspace/
      - ./gamslice.txt/:/opt/gams/gams25.0_linux_x64_64_sfx/gamslice.txt

