version: "3.6"
services:
  gams:
    build: .
#    command: bash -c "/opt/gams/gams25.0_linux_x64_64_sfx/gams"
    stdin_open: true
    tty: true
    volumes:
      - ./sourceandstudies/:/workspace/

